### ISSUE TITLE
Add minimum permissions to workflow

### ISSUE THREAD

**Issue by gabibguti** [bits-and-blooms/bitset#118]
Adding minimum permissions to your workflows help keep your repository safe against supply-chain attacks. I see the repo only uses one workflow `test.yml` for testing and this workflow just needs `contents: read` permission to run `actions/checkout`. If you agree with these changes, I can open a PR!

This is considered good-practice and recommended by [GitHub itself](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) and other security tools, such as [Scorecards](https://github.com/ossf/scorecard) and [StepSecurity](https://github.com/step-security).

##### Additional context
I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by willf** [comment]
I like it!

**Comment by lemire** [comment]
It is not controversial.

Go !!!
