### ISSUE TITLE
ReadFrom trashes the old instace

### ISSUE THREAD

**Issue by omerfirmak** [bits-and-blooms/bitset#121]
`ReadFrom` creates a new `bitset` and overrides the previous one when it does not encounter any error during the process.

https://github.com/bits-and-blooms/bitset/blob/d53c44e11e2ad25523c7676c8f498ea11f50eff1/bitset.go#L949-L968

For applications that constantly marshal/unmarshal `bitset`s, this is a huge problem. What `ReadFrom` should do instead is try to reuse the existing `bitset` and the underlying `[]uint64` it has. It should avoid creating any one-time temporary heap buffers as well.

To be honest I don't know why it works like that but the fact that `ReadFrom` does not modify the existing instance if it encounters an error makes this a little tricky.

**Comment by lemire** [comment]
I agree. Let us fix that in the next release.
