### ISSUE TITLE
Flagging supply-chain security issues

### ISSUE THREAD

**Issue by gabibguti** [bits-and-blooms/bitset#138]
Flagging supply-chain security issues can help you, well, prevent supply-chain attacks. Supply-chain attacks aim for your development, build and release weaknesses. That's why, when we use minimum permissions for actions and reference actions by commit SHA even on test workflows, we help protecting the development process from malicious actions.

In this repository, we have already worked to flag and fix a few supply-chain security issues. To flag more issues like that we can use [Scorecard](https://github.com/ossf/scorecard) security tool and receive alerts in GitHub's Security Dashboard. If you are willing to try out the tool, let me know, I can open a PR.

#### Additional Context

Hi again! I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by lemire** [comment]
@gabibguti Please do so.
