### ISSUE TITLE
ReadFrom Slow!!!

### ISSUE THREAD

**Issue by king526** [bits-and-blooms/bitset#141]
https://github.com/bits-and-blooms/bitset/blob/e052c0037b13041fe61390305eac4fb73e78c695/bitset.go#L986

ReadFrom method is too bad ;  it take too much time!!!  ( I have to replace version to v1.2.0)

**Comment by lemire** [comment]
This is a really badly prepared issue, with no analysis, no benchmarking.

Still. I agree with the sentiment.
