### ISSUE TITLE
github actions with endianess tests

### ISSUE THREAD

**Issue by gaissmai** [bits-and-blooms/bitset#164]
Hi again, could you imagine integrating CI tests for systems with different endianess into the CI pipeline?

Small note on passing, there is a typo in the testname: `TestExendOnBoundary`

thanks a lot for this great library!

**Comment by lemire** [comment]
@gaissmai What is the big endian platform that you are relying on in your work?

**Comment by gaissmai** [comment]
To be honest, I do not rely on any big endian platform, but I use your library with precalculated serialized bitsets.

**Comment by lemire** [comment]
I am inviting a pull request.

I am also closing this issue. If you believe that there is an issue with big endian systems, please provide details.

**Comment by gaissmai** [comment]
just for completeness:

tested it now with QEMU emulation locally, there was no problem with big endianess:

```
root@ubuntu:/tmp/bitset# lscpu | head
Architecture:                         s390x
CPU op-mode(s):                       32-bit, 64-bit
Byte Order:                           Big Endian
CPU(s):                               2
On-line CPU(s) list:                  0,1
Vendor ID:                            IBM/S390
Machine type:                         3906
Thread(s) per core:                   1
Core(s) per socket:                   1
Socket(s) per book:                   1

root@ubuntu:/tmp/bitset# go list 
github.com/bits-and-blooms/bitset

root@ubuntu:/tmp/bitset# go test
PASS
ok  	github.com/bits-and-blooms/bitset	2.433s

```
