### ISSUE TITLE
1.19.0 missing popcount function

### ISSUE THREAD

**Issue by winterspite** [bits-and-blooms/bitset#190]
![image](https://github.com/user-attachments/assets/6417b766-6a4c-494c-9018-1e650c110b60)
Updated to 1.19.0 and am failing to compile my application. It looks like `popcount` is referenced but not defined in [this PR](https://github.com/bits-and-blooms/bitset/pull/184/files#diff-facc6619bcab209dc2574fcd7300694b708077b8c2f5174712084b5866d619d3R1455)

**Comment by lemire** [comment]
Thanks for the report. I made a mistake in the release. I have since updated the commit hash. Please try again.

**Comment by peterbourgon** [comment]
In the context of Go and Go modules, once a semver-compatible tag (like v1.19.0) is defined at some specific git SHA, it can't be updated/changed afterwards. Doing so breaks the Go modules infrastructure, and all downstream consumers.

Concretely, the fact that this repo re-assigned `v1.19.0` initially as [2108e732c5068c26bdaca9d3c283cf52770519db] and then changed that tag to be [a512614d907094b779eec329c8f8054cd511a302] was invalid, and broke Go modules.

At this point, the `bitset` repo needs to define a new `v1.19.1` tag at [a512614](https://github.com/bits-and-blooms/bitset/commit/a512614d907094b779eec329c8f8054cd511a302); create a new release at that tag; and, ideally, should [retract](https://go.dev/ref/mod#go-mod-file-retract) the existing `v1.19.0` release.

**Comment by nadeemc** [comment]
Agreed, a new v1.19.1 tagged release would be very helpful. Having a cached version of the original tag on v1.19.0 made it difficult to clear the package caches and get the corrected tag for v1.19.0 downloaded instead.

**Comment by lemire** [comment]
1.19.1 is out!!!
