### ISSUE TITLE
From() without a new allocation

### ISSUE THREAD

**Issue by dececx** [bits-and-blooms/bitset#85]
Do you think it would be reasonable to add something like:
```
func (b *BitSet) SetBitsetFrom(buf []uint64) {
  b.length = ulen(len(buf)) * 64
  b.set = buf
}
```
It's basically `From()` without a new allocation. Escape analysis seems to force a heap allocation with the current From() and I'm trying to avoid it.

**Comment by lemire** [comment]
Sounds reasonable.

**Comment by willf** [comment]
@dececx Do you want to write a PR?

**Comment by lemire** [comment]
Note that this issue is still reasonable and could be fixed rather easily.

For people reading this, the idea is that you'd avoid creating a new Bitset instance (which `From` does).
