### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by willf** [bits-and-blooms/bitset#89]
I am not writing Go code anymore. Would someone like to take over as maintainer? @lemire ?

**Comment by lemire** [comment]
@willf That's what I've been doing "de facto". I may continue.

**Comment by objque** [comment]
It sad news, but what the future of [willf/bloom](https://github.com/willf/bloom)?
I think to fork it and tweak a little bit

**Comment by lemire** [comment]
You can fork it, of course, but I expect that the project will go on.

**Comment by willf** [comment]
You can submit PRs here, and @lemire will review. I'm wondering if it's worth moving to an Org that Daniel and I or others can admin.

**Comment by lemire** [comment]
@willf Makes no difference to me.

**Comment by moredure** [comment]
@lemire https://github.com/bits-and-blooms/bloom/issues/60
