### ISSUE TITLE
NewAll - create a new bitset with everything set to 1

### ISSUE THREAD

**Issue by fommil** [bits-and-blooms/bitset#93]
I have a usecase where I would like to create a bitset with everything initially set to 1 since that is more common for me than initial values of 0. I'm currently using `.New(size).FlipRange(0, size)` but it feels like a dedicated constructor would be faster (I guess I could also use `bitset.From` but that requires me to duplicate the `wordsNeeded` arithmetic...).

As an aside; are there any perf comparisons or documentation to `[]bool` ? I couldn't even find out what the Go representation of `[]bool` is (on Java there is a high chance that 64 bits will be used to represent each entry), so I'm using this package to be on the safe side 😬

**Comment by lemire** [comment]
> As an aside; are there any perf comparisons or documentation to []bool ?

A `bool` uses 1 byte so that would be 8 times the memory usage of a `bitset`, along the loss of word-level parallelism.

**Comment by lemire** [comment]
> I'm currently using .New(size).FlipRange(0, size) but it feels like a dedicated constructor would be faster

Do you have benchmarks?

What is your rationale for it being faster?

**Comment by fommil** [comment]
I'm probably overthinking it to be honest, there's never going to be more than ~100 invocations in any given run of my application, so I doubt any benchmark will ever flag up a problem unless I was doing this a million times; it just seemed like a nice API improvement. Please feel free to close as WontFix if you feel this would pollute the API, I am starting to regret bother you now 😆 !

**Comment by lemire** [comment]
I am closing.

Note that I do not expect that it would be faster.
